services:
  prometheus:
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.central.yml'
    networks:
      - monitoring
      - proxy-network
    depends_on:
      - blackbox-exporter
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`${PROMETHEUS_URL}`)"
      - "traefik.http.routers.prometheus.tls=true"

  grafana:
    image: grafana/grafana:11.6.2
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - monitoring
      - proxy-network
    expose:
      - 3000
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_URL}`)"
      - "traefik.http.routers.grafana.tls=true"

  alertmanager:
    image: prom/alertmanager:v0.28.1
    restart: unless-stopped
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - monitoring
      - proxy-network
    expose:
      - 9093
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`${ALERTMANAGER_URL}`)"
      - "traefik.http.routers.alertmanager.tls=true"

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.26.0
    restart: unless-stopped
    volumes:
      - ./blackbox:/etc/blackbox_exporter
    networks:
      - monitoring
      - proxy-network
    expose:
      - 9115
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackbox.rule=Host(`${BLACKBOX_URL}`)"
      - "traefik.http.routers.blackbox.tls=true"

volumes:
  grafana-data:

networks:
  proxy-network:
    external: true
