groups:
  - name: Blackbox
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Blackbox probe failed for {{ $labels.instance }}"
          description: "Probe failed!\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"

      - alert: BlackboxProbeHttpFailure
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Blackbox probe HTTP failure for {{ $labels.instance }}."
          description: "HTTP status code is not 200 - 399!\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: 0 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 3
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Blackbox SSL certificate for {{ $labels.instance }} will expire soon."
          description: "SSL certificate expires in less than 3 days\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"

      - alert: BlackboxSslCertificateExpired
        expr: round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "Blackbox SSL certificate for {{ $labels.instance }} has expired!"
          description: "SSL certificate has expired already\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
