modules:
  http_2xx:
    prober: http
    timeout: 10s
    http:
      method: GET
      fail_if_not_ssl: true
      follow_redirects: true
      preferred_ip_protocol: "ip4"
      valid_http_versions:
        - "HTTP/1.1"
        - "HTTP/2.0"

  smtp_starttls:
    prober: tcp
    timeout: 20s
    tcp:
      preferred_ip_protocol: "ip4"
      query_response:
        - expect: "^220 ([^ ]+) ESMTP(.?)$"
        - send: "EHLO prober\r"
        - expect: "^250-STARTTLS"
        - send: "STARTTLS\r"
        - expect: "^220"
        - starttls: true
        - send: "EHLO prober\r"
        - expect: "^250-AUTH"
        - send: "QUIT\r"
